[package]
name = "nubisync-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file = "../../LICENSE"
repository.workspace = true

[[bin]]
name = "nubisync"
path = "src/main.rs"

[dependencies]
nubisync-auth = { path = "../nubisync-auth" }
nubisync-core = { path = "../nubisync-core" }
nubisync-daemon = { path = "../nubisync-daemon" }
nubisync-drive = { path = "../nubisync-drive" }
nubisync-storage = { path = "../nubisync-storage" }
rpassword.workspace = true
thiserror.workspace = true
tiny_http.workspace = true
url.workspace = true
webbrowser.workspace = true
