[package]
name = "nubisync-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file = "../../LICENSE"
repository.workspace = true

[[bin]]
name = "nubisyncd"
path = "src/main.rs"

[dependencies]
nubisync-core = { path = "../nubisync-core" }
nubisync-drive = { path = "../nubisync-drive" }
nubisync-storage = { path = "../nubisync-storage" }
nubisync-sync = { path = "../nubisync-sync" }
thiserror.workspace = true
